.TH "character" 3 "Сб 22 Май 2021" "My Project_help_Mult" \" -*- nroff -*-
.ad l
.nh
.SH NAME
character \- - персонажи
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBbiven::HouseDraw\fP (int x, int y, double sizeX, double sizeY, double GableUp, double GableX, double roofRight, double roofLeft)"
.br
.RI "данная функция рисует самостийный домик "
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBЗаметки\fP
.RS 4
Библиотека начинающего программиста \fBBivenLib\&.h\fP это собрание персонажей анимации первого мультика-программы\&. в первой версии в библиотеку включены следующие функции-персонажи BoyDraw - мужчина SunDraw - солнце TreeDraw - дерево HouseDraw - домик
.RE
.PP
} 
.SH "Функции"
.PP 
.SS "void biven::HouseDraw (int x, int y, double sizeX, double sizeY, double GableUp, double GableX, double roofRight, double roofLeft)"

.PP
данная функция рисует самостийный домик 
.PP
\fBАргументы\fP
.RS 4
\fIx\fP - координата х точки отсчета (относительной системы координат) 
.br
\fIy\fP - координата y точки отсчета (относительной системы координат) 
.br
\fIsizeX\fP - множитель, определяющий размер домика
.RE
.PP
.PP
.nf
void HouseDraw (int x, int y, double sizeX, double sizeY, double GableUp, double GableX, double roofRight, double roofLeft);
.fi
.PP
 
.PP
См\&. определение в файле BivenLib\&.h строка 126
.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project_help_Mult из исходного текста\&.
