.TH "md__d__school__xD0_x9A_xD0_x9F_xD0_x9A__xD0_xA0_xD0_xB5_xD0_xBF_xD0_xBE_xD0_xB7_xD0_xB8_xD1_x82_xD0_xBE_xD1_x80_xD0_xB8_xD0_xB9_igorbegining__project_by_yourself__r_e_a_d_m_e" 3 "Сб 22 Май 2021" "My Project_help_Mult" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__d__school__xD0_x9A_xD0_x9F_xD0_x9A__xD0_xA0_xD0_xB5_xD0_xBF_xD0_xBE_xD0_xB7_xD0_xB8_xD1_x82_xD0_xBE_xD1_x80_xD0_xB8_xD0_xB9_igorbegining__project_by_yourself__r_e_a_d_m_e \- igorbegining 
Начало КПК с ded Мультик в рамках КПК физтех\&. 
.PP
 Содержание
.PP
.IP "1." 4
Общее описание сценария\&.
.IP "2." 4
Словарь терминов\&.
.IP "3." 4
Пояснение функций\&. 
.PP

.PP
.IP "1." 4
Общее описания сценария
.PP
.PP
Начала программирования\&. Начинаем с рисования объектов посредством линий, простых фигур, таких как - окружность, квадрат\&.
.PP
Рисование производим с помощью пакета 'Тупой художник' TXLib\&.
.PP
Множество строчек кода, которыми рисуется объект объединяются в функцию, которая в свою очередь имеет параметры, влияющие на координаты характерных точек объекта т\&.е\&. на размеры объекта и взаимное расположение частей объекта\&.
.PP
С помощью цикла while производим анимацию - движение объектов, а также множественное копирование\&.
.PP
Сюжет фильма навеяло из космоса\&. 12 апреля 60 лет полета человека в космос\&. И тяга человечество к колонизации других планет\&.
.PP
Фильм состоит из сцен\&. Сцена первая: 'Serenity' - безмятежность показывает безымянную планету\&. все объекты нарисованы с помощью функции POLYGON это позволяет трансформировать объекты и не беспокоиться, что собъются цвета объектов\&. пример кода - гора центральная: 
.PP
 txSetColor (TX_LIGHTGRAY); 
.PP
.nf
txSetFillColor (RGB (200, 192, 170));

POINT MountainCentral [13] = {{166, 457}, {439, 225}, {480, 263}, {519, 245}, {561, 264}, {615, 249}, {666, 225},

                              {766, 231}, {928, 446}, {840, 432}, {648, 432}, {438, 443}, {278, 443}};

txPolygon (MountainCentral, 13);

.fi
.PP
 
.PP
.PP
.PP
Сцена вторая Высадка дисанта (Disembarkation), включающыя в себя также функцию посадки звездолета (Landskape)\&. Прохождение солнц (их кстати два) показывает, что десант высаживался не одни местные сутки\&.
.PP
.PP
Сцена третья
.PP
Строительство лагеря (ConstructionCamp)\&.
.PP
Здесь колонисты выбирают место строительства лагеря и строят дома\&.
.PP
Сцена четвертая: выращивание сада PlantingGarden, сцена состоит из GardenStart - посадка сада, HeightGarden - роста сада\&.
.PP
И конечно начальные (StartTitles) и конечные титры (EndTitles)
.PP
 
